# Multiple distinct keys can be held on a Yubikey in PIV mode. One socket will be created for each keyslot. 
# It's a bad idea to do this if you use the PIV slots for their intended purposes (i.e. don't do this except on a PIV device you will only use for yubikey-agent).
- keyslots:
  # Slot 9A: PIV Authentication
  # On a config-less installation, this slot will be used
  - Authentication:
    # Keyslots are allocated a name which will be used as a socket suffix.
    - name: "main"
    # Keyslots may have one of two purposes: signature (for authentication / signing; ex. SSH) and encryption (for ECDH). Default: "signature"
    - purpose: "signature"
  # Slot 9C: Digital Signature (note: this slot *could* be used for encryption; the slot name of Signature does not restrict it's use)
  - Signature:
    - name: "repositories"
  # Slot 9D: Key Management
  - KeyManagement:
    - name: "backup"
  # Slot 9E: Card Authentication (null = socket will not be run / keys will not be configured)
  - CardAuthentication:
  # Additional "Retired" Slots which can be used for additional keys
  - 82:
    - name: "testing-signature"
    - purpose: "signature"
  - 83: 
    - name: "testing-encryption"
    - purpose: "encryption"
  - 84:
  - 85:
  - 86:
  - 87:
  - 88:
  - 89:
  - 8a:
  - 8b:
  - 8c:
  - 8d:
  - 8e:
  - 8f:
  - 90:
  - 91:
  - 92:
  - 93:
  - 94:
  - 95:
# attestation: when true, attestation certificates are printed during key generation (-setup) and when dumping keys (-dump). The attestation string
# contains the base64-encoded attestation and intermediate certificates separated by a pipe (|). These certificates can be used to verify whether
# a paticular public key was generated on Yubikey hardware and the relevant key policies. Default: false.
- attestation: false